window.YERIEL_DRIVE_GALLERY = [
  { label: 'Fotografía de artista', src: 'assets/photos/photo-01.jpg' },
  { label: 'Retrato de estudio', src: 'assets/photos/photo-02.jpg' },
  { label: 'Retrato editorial', src: 'assets/photos/photo-03.jpg' },
  { label: 'Cobertura de figura pública', src: 'assets/photos/photo-04.jpg' },
  { label: 'Cobertura de evento', src: 'assets/photos/photo-05.jpg' },
  { label: 'Música en vivo', src: 'assets/photos/photo-06.jpg' },
  { label: 'Fotografía artística', src: 'assets/photos/photo-07.jpg' },
  { label: 'Fotografía artística', src: 'assets/photos/photo-08.jpg' },
  { label: 'Fotografía artística', src: 'assets/photos/photo-09.jpg' },
  { label: 'Fotografía artística', src: 'assets/photos/photo-10.jpg' },
  { label: 'Fotografía artística', src: 'assets/photos/photo-11.jpg' },
  { label: 'Fotografía artística', src: 'assets/photos/photo-12.jpg' },
  { label: 'Fotografía de concierto', src: 'assets/photos/photo-13.jpg' },
  { label: 'Fotografía de concierto', src: 'assets/photos/photo-14.jpg' },
  { label: 'Fotografía de evento', src: 'assets/photos/photo-15.jpg' },
  { label: 'Fotografía de evento', src: 'assets/photos/photo-16.jpg' },
  { label: 'Fotografía de evento', src: 'assets/photos/photo-17.jpg' },
  { label: 'Retrato', src: 'assets/photos/photo-18.jpg' },
  { label: 'Fotografía de artista', src: 'assets/photos/photo-19.jpg' },
  { label: 'Fotografía de artista', src: 'assets/photos/photo-20.jpg' },
  { label: 'Fotografía de artista', src: 'assets/photos/photo-21.jpg' },
  { label: 'Fotografía de artista', src: 'assets/photos/photo-22.jpg' },
  { label: 'Fotografía de artista', src: 'assets/photos/photo-23.jpg' },
  { label: 'Fotografía de artista', src: 'assets/photos/photo-24.jpg' },
  { label: 'Cobertura artística', src: 'assets/photos/photo-25.jpg' },
  { label: 'Presentación en vivo', src: 'assets/photos/photo-26.jpg' },
  { label: 'Retrato de artista', src: 'assets/photos/photo-27.jpg' },
  { label: 'Retrato de artista', src: 'assets/photos/photo-28.jpg' },
];
